### ISSUE TITLE
Sparse Tensor Project TODO list

### ISSUE THREAD

**Issue by reminisce** [reminisce/mxnet#5]
- [ ] dot(csr, rsp) = dns impl/unit test/benchmark

- [ ] dot(csr.T, rsp) = rsp2 impl/unit test/benchmark

- [ ] Change int to int64_t to support large numbers in cast_storage and dot

- [ ] Refactor sparse tensor code (put ndarray.py, sparse_ndarray.py, and ndarray_utils.py into ndarray folder, etc.)

- [ ] Move elemwise sum to a util file from comm.h and support general OP such as minus, min, max

- [ ] Remove c api call for getting stype from a handle in frontend

- [ ] Move dot impl to a dot-inl.h, dot.cc, dot.cu
